mysql/init.sql
- 데이터베이스 초기화 쿼리 추가: DB 및 테이블 생성, 샘플 데이터 삽입
=> etc: 데이터베이스 정보 수정

mysql/init.sql
- 샘플데이터(회원) PK 변경: 영문 + 9자리 -> 영문 + 6자리
=> etc: 데이터베이스 수정

src/main/java/com/gongzone/central/sample/controller/SampleMemberController.java, src/main/java/com/gongzone/central/sample/domain/SampleMember.java, src/main/java/com/gongzone/central/sample/mapper/SampleMemberMapper.java, src/main/java/com/gongzone/central/sample/service/SampleMemberService.java, src/main/java/com/gongzone/central/sample/service/SampleMemberServiceImpl.java, src/main/resources/application-db.properties, src/main/resources/application.properties, src/main/resources/mapper/SampleMapper.xml
=> etc: 프로젝트 초기 설정

src/main/java/com/gongzone/central/utils/StatusCode.java, src/main/java/com/gongzone/central/utils/TypeCode.java
=> refactor: enum 코드명 수정

src/main/java/com/gongzone/central/location/controller/LocationController.java, src/main/java/com/gongzone/central/location/domain/LocationSearch.java, src/main/java/com/gongzone/central/location/mapper/LocationMapper.java, src/main/java/com/gongzone/central/location/service/LocationService.java, src/main/java/com/gongzone/central/location/service/LocationServiceImpl.java, src/main/java/com/gongzone/central/member/login/security/JwtRequestFilter.java, src/main/java/com/gongzone/central/party/accept/controller/AcceptController.java, src/main/java/com/gongzone/central/party/accept/domain/AcceptDetail.java, src/main/java/com/gongzone/central/party/accept/domain/AcceptMember.java, src/main/resources/mapper/location/LocationMapper.xml, src/main/resources/mapper/party/PartyMapper.xml
=> [GZ-27]✨feat:Location Search added

src/main/java/com/gongzone/central/announce/controller/AnnounceController.java, src/main/java/com/gongzone/central/announce/domain/Announce.java, src/main/java/com/gongzone/central/announce/mapper/AnnounceMapper.java, src/main/java/com/gongzone/central/announce/service/AnnouceService.java, src/main/java/com/gongzone/central/announce/service/AnnounceServiceImpl.java, src/main/resources/mapper/announce/Announce.xml
=> [GZ-32] feat: announce

src/main/java/com/gongzone/central/party/accept/controller/AcceptController.java, src/main/java/com/gongzone/central/party/accept/mapper/AcceptMapper.java, src/main/java/com/gongzone/central/party/accept/service/AcceptService.java, src/main/java/com/gongzone/central/party/accept/service/AcceptServiceImpl.java, src/main/resources/mapper/party/PartyMapper.xml
=> [GZ-26]♻🐛refactoring:party bug fix & refactoring

src/main/java/com/gongzone/central/member/report/controller/ReportController.java, src/main/resources/mapper/member/ReportMapper.xml
=> [GZ-26]🐛fix:report bug fixed

src/main/java/com/gongzone/central/board/domain/BoardReply.java, src/main/java/com/gongzone/central/party/accept/domain/AcceptDetail.java, src/main/java/com/gongzone/central/party/accept/service/AcceptServiceImpl.java, src/main/resources/mapper/board/BoardMapper.xml, src/main/resources/mapper/party/PartyMapper.xml
=> [GZ-26]♻refactoring:reply added

src/main/java/com/gongzone/central/party/accept/controller/AcceptController.java, src/main/java/com/gongzone/central/party/accept/domain/PartyMemberPurchase.java, src/main/java/com/gongzone/central/party/accept/mapper/AcceptMapper.java, src/main/java/com/gongzone/central/party/accept/service/AcceptService.java, src/main/java/com/gongzone/central/party/accept/service/AcceptServiceImpl.java, src/main/resources/mapper/party/PartyMapper.xml
=> [GZ-26]✨feat:party payment info

src/main/java/com/gongzone/central/point/service/PointServiceImpl.java
- 파티원 결제 시 memberPointNo가 아닌 memberNo를 사용하던 점 수정
=> [GZ-35] :bug: fix: Fixed party purchaing issue

src/main/java/com/gongzone/central/member/login/controller/LoginController.java, src/main/java/com/gongzone/central/member/login/mapper/LoginMapper.java, src/main/java/com/gongzone/central/member/login/security/JwtRequestFilter.java, src/main/java/com/gongzone/central/member/login/service/LoginLogService.java, src/main/java/com/gongzone/central/member/login/service/LoginLogServiceImpl.java, src/main/java/com/gongzone/central/member/socialLogin/google/service/GoogleService.java, src/main/java/com/gongzone/central/member/socialLogin/kakao/service/KakaoService.java, src/main/java/com/gongzone/central/member/socialLogin/naver/service/NaverService.java, src/main/resources/mapper/member/LoginMapper.xml
=> [GZ-17]feat:login log

src/main/java/com/gongzone/central/party/accept/mapper/AcceptMapper.java, src/main/java/com/gongzone/central/party/accept/service/AcceptService.java, src/main/java/com/gongzone/central/party/accept/service/AcceptServiceImpl.java, src/main/resources/mapper/party/PartyMapper.xml
=> [GZ-26]🐛fix:party status bug fixed

src/main/java/com/gongzone/central/party/accept/service/AcceptServiceImpl.java
- 모집종료 시 파티장이 결제현황 테이블에 삽입되어 비정상적으로 동작하던 점 수정
=> :bug: fix: Fixed party match issue

src/main/java/com/gongzone/central/location/domain/LocationSearch.java, src/main/resources/mapper/location/LocationMapper.xml
=> [GZ-26]♻refactoring:refactoring

src/main/java/com/gongzone/central/common/constants/ConstantsString.java, src/main/java/com/gongzone/central/party/after/mapper/PartyAfterMapper.java, src/main/java/com/gongzone/central/party/after/service/PartyAfterServiceImpl.java, src/main/java/com/gongzone/central/party/after/service/admin/AdminPartyAfterServiceImpl.java, src/main/resources/mapper/party/PartyAfterMapper.xml
=> [GZ-35] :sparkles: feat: Implement party after process alert

src/main/java/com/gongzone/central/common/pagination/Pagination.java, src/main/java/com/gongzone/central/point/controller/PointController.java, src/main/java/com/gongzone/central/point/mapper/PointHistoryMapper.java, src/main/java/com/gongzone/central/point/service/PointHistoryService.java, src/main/java/com/gongzone/central/point/service/impl/PointHistoryServiceImpl.java, src/main/resources/mapper/point/PointHistoryMapper.xml
=> [GZ-15] :sparkles: feat: Implement point history pagination feature

src/main/java/com/gongzone/central/board/controller/BoardController.java, src/main/java/com/gongzone/central/board/domain/BoardMyPage.java, src/main/java/com/gongzone/central/board/mapper/BoardMapper.java, src/main/java/com/gongzone/central/board/service/BoardService.java, src/main/java/com/gongzone/central/board/service/BoardServiceImpl.java, src/main/resources/mapper/board/BoardMapper.xml
=> [GZ-17]feat: board wishList

src/main/java/com/gongzone/central/member/socialLogin/google/controller/GoogleController.java, src/main/java/com/gongzone/central/member/socialLogin/kakao/controller/KakaoController.java, src/main/java/com/gongzone/central/member/socialLogin/kakao/service/KakaoService.java, src/main/java/com/gongzone/central/member/socialLogin/naver/controller/NaverController.java, src/main/java/com/gongzone/central/member/socialLogin/naver/service/NaverService.java
=> [GZ-17]feat: social login error

src/main/java/com/gongzone/central/member/Management/service/ManagementServiceImpl.java, src/main/java/com/gongzone/central/member/question/service/QuestionServiceImpl.java, src/main/java/com/gongzone/central/member/report/service/ReportServiceImpl.java
=> [GZ-17]refectoring: typeCode

src/main/java/com/gongzone/central/location/domain/LocationSearch.java, src/main/java/com/gongzone/central/party/accept/domain/AcceptMember.java, src/main/resources/mapper/location/LocationMapper.xml, src/main/resources/mapper/party/PartyMapper.xml
=> [GZ-26]🐛fix:bug fix
